server:
  port: 8082
  wait-time-in-ms-when-sync-empty: 3000

spring:
  datasource:
    url: jdbc:postgresql://postgres_db:5432/db_cliente
    username: user
    password: senha1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application-version: 1.0
