server:
  port: 8081
  wait-time-in-ms-when-sync-empty: 3000

spring:
  datasource:
    url: jdbc:mysql://mysql_db:3306/db_comercio
    username: user
    password: senha1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

application-version: 1.0
