name: Continuous Integration with Github Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ClienteService, ComercioService, ProdutoService, ConfigServer]

    steps:
      - uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'adopt'
          cache: maven

      - name: Build Application JAR
        working-directory: ${{ matrix.service }}
        run: mvn -B package

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/microservice3dbs_${{ matrix.service }}:latest ${{ matrix.service }}

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/microservice3dbs_${{ matrix.service }}:latest
