name: Build and Push to Azure Container Registry

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - service: ConfigServer
            image: microservice3dbs_config
          - service: ClienteService
            image: microservice3dbs_cliente
          - service: ComercioService
            image: microservice3dbs_comercio
          - service: ProdutoService
            image: microservice3dbs_produto

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Compilar microserviço com Maven
        working-directory: ${{ matrix.service }}
        run: mvn clean package

      - name: Login no Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
          username: ${{ secrets.AZ_DOCKER_USERNAME }}
          password: ${{ secrets.AZ_DOCKER_PASSWORD }}

      - name: Build da imagem Docker
        run: |
          docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}/${{ matrix.image }}:latest ./${{ matrix.service }}

      - name: Push da imagem para o ACR
        run: |
          docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/${{ matrix.image }}:latest
